feat(PoExtractor): add single file output
OrchardCoreContrib/OrchardCoreContrib.PoExtractor pull request #94
Opened 2024-06-17 18:54 UTC by VincenzoCarlino

Implementation of: #93

2024-06-17 19:02 UTC, hishamco requested changes
It would be nice to have few unit tests, there're many corner cases that we need to test, to ensure nothing is broken

2024-06-17 19:02 UTC, hishamco commented on src/OrchardCoreContrib.PoExtractor/Program.cs
> +        Console.WriteLine("  -s, --single messages.pot              Get single output file.");
```suggestion
        Console.WriteLine("  -s, --single messages.pot              Specifices the single output file.");
```

2024-06-17 20:05 UTC, VincenzoCarlino commented
> It would be nice to have few unit tests, there're many corner cases that we need to test, to ensure nothing is broken

Look at this [commit](https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/pull/94/commits/479751a4634e4b962a9cd7af95d6c6bdefaaefd4)

It's a preview of some kinds of test we can do.
All code is inside the main static function, so we can test it as I've done it in this commit, or we try to extract the code from main in something more testable.
Let me know if you like it.

2024-06-19 18:26 UTC, hishamco commented
Thanks, @VincenzoCarlino, we might need to test more cases such as if there's a PO file with the same specified file

2024-06-19 20:08 UTC, VincenzoCarlino commented
> Thanks, @VincenzoCarlino, we might need to test more cases such as if there's a PO file with the same specified file

Yes @hishamco , this is just an example of the structure of tests. Tomorrow I'll add more tests.

2024-06-19 20:09 UTC, hishamco commented
Please fix the build

2024-06-26 10:28 UTC, VincenzoCarlino commented
Hi @hishamco , I think that we don't have an easy way to test output files... using the real filesystem in the pipeline is not a good option. Do you have any suggestions?

2024-06-28 00:52 UTC, hishamco commented
Let me try ..

2024-06-28 01:09 UTC, hishamco commented
https://github.com/OrchardCMS/OrchardCore/blob/ba5e8c03c8f3aef138651184317e4859dab7adfd/src/OrchardCore/OrchardCore.Localization.Core/DefaultPluralRuleProvider.cs#L61-L73

2024-06-29 07:09 UTC, VincenzoCarlino commented
Ok @hishamco I'll wait for your commit, let me know if I can do something.

2024-07-24 12:14 UTC, hishamco commented
Sorry for the late, I will struggle to have a look today because we need to finalize this and publish a release before Orchard Core 2.0.0

2024-08-12 13:24 UTC, VincenzoCarlino commented
> Sorry for the late, I will struggle to have a look today because we need to finalize this and publish a release before Orchard Core 2.0.0

Hello, any update?
Thanks @hishamco

2024-08-12 17:41 UTC, hishamco commented
Seems I forgot this one, let me check it tonight if it's possible. My plan to publish a release ASAP and will be a part of OC 2.0.0

2024-08-12 22:25 UTC, hishamco commented
I suggest trying this PR from `Program.cs` then we can focus on make the CLI commands testable

2024-08-12 22:48 UTC, hishamco commented
@VincenzoCarlino please remove the changes in the test project, then I will merge, this not take so long to merge

2024-08-15 09:02 UTC, hishamco approved these changes

2024-08-15 09:02 UTC, merged

2024-08-15 09:02 UTC, hishamco commented
Thanks for your contribution @VincenzoCarlino